Imports

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

Read Kaggle Data

In [ ]:
earthquake = pd.read_csv("earthquake1826_2026.csv")

Convert Time to DateTime and Extract

In [ ]:
earthquake["time"] = pd.to_datetime(earthquake["time"], format='ISO8601')

earthquake["year"] = earthquake["time"].dt.year
earthquake["month"] = earthquake["time"].dt.month

Create magnitude categories

In [ ]:
def mag_category(mag):
  if mag < 6.0:
    return "Moderate"
  elif mag < 7.0:
    return "Strong"
  else:
    return "Major"

earthquake["magnitude_category"] = earthquake["mag"].apply(mag_category)

Input and Output selection

In [ ]:
X = earthquake[["latitude", "longitude", "year", "month"]]
y = earthquake["magnitude_category"]

Training and Testing

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

Train Model

In [ ]:
forests_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    random_state=42,
    class_weight="balanced"
)

forests_model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

Predictions

In [ ]:
predictions = forests_model.predict(X_test)

Evaluate Model

In [ ]:
acc = accuracy_score(y_test, predictions)
print(f"Accuracy: {acc}")

print(classification_report(y_test, predictions))

print(confusion_matrix(y_test, predictions))

Accuracy: 0.8733503016591252
              precision    recall  f1-score   support

       Major       0.29      0.07      0.12       322
    Moderate       0.90      0.97      0.93     18309
      Strong       0.54      0.29      0.37      2585

    accuracy                           0.87     21216
   macro avg       0.58      0.44      0.48     21216
weighted avg       0.85      0.87      0.85     21216

[[   24   182   116]
 [   22 17765   522]
 [   37  1808   740]]


Example Earthquake Testing

In [ ]:
eg_earthquake = pd.DataFrame({
    "latitude": [7.7749],
    "longitude": [5.4194],
    "year": [2023],
    "month": [1]
})

pred_category = forests_model.predict(eg_earthquake)
print(f"Predicted Magnitude Category: {pred_category[0]}")

Predicted Magnitude Category: Moderate
